# -*- coding: utf-8 -*-
"""Lesson3#LANGUAGE บริการด้านประมวลผลข้อความภาษาไทยรอบด้าน เช่น Word Segmentation, POS Tagging, Named Entity Recognition  SENTIMENT ANALYSIS บริการวิเคราะห์ความคิดเห็นและอารมณ์ - Emoji Predicti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17swwHwWIUwNw9yNElVnItPkH_CqkBkqL
"""

import requests
 
moji_list =[['🙂','😄','😁','😆','😀','😊','😃'],
['😢','😥','😰','😓','🙁','😟','😞','😔','😣','😫','😩'],
['😡','😠','😤','😖'],
['🙄','😒','😑','😕'],
['😱'],
['😨','😧','😦'],
['😮','😲','😯'],
['😴','😪'],
['😋','😜','😝','😛'],
['😍','💕','😘','😚','😙','😗'],
['😌'],
['😐'],
['😷'],
['😳'],
['😵'],
['💔'],
['😎','😈'],
['🙃','😏','😂','😭'],
['😬','😅','😶'],
['😉'],
['💖','💙','💚','💗','💓','💜','💘','💛'],
['😇']]
 
url = "https://api.aiforthai.in.th/emoji"
 
text = 'ความรักเป็นสิ่งสวยงาม'
 
params = {'text':text}
 
headers = {
    'Apikey': "t5xX0LLizRkhF63izmJ7YUc6AiQHhs17"
    }
 
response = requests.get(url, params=params, headers=headers)
 
keys=response.json().keys()
 
emoji = [moji_list[int(k)][0] for k in keys]
 
print(emoji)

