# -*- coding: utf-8 -*-
"""Lesson2# LANGUAGE : MACHINE TRANSLATION บริการแปลภาษา.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sBklvEbzZ8xPa1PUFpEV9BOvGr934iCx
"""

import requests
from urllib.parse import quote_plus
 
text = 'สวัสดี'
 
url = 'https://api.aiforthai.in.th/th-zh-nmt/' +quote_plus(text)
 
headers = {
    'Apikey': "t5xX0LLizRkhF63izmJ7YUc6AiQHhs17",
    }
 
response = requests.get(url, headers=headers)
 
print(response.text)

import requests
from urllib.parse import quote_plus
 
text = '您好'
 
url = 'https://api.aiforthai.in.th/zh-th-nmt/' +quote_plus(text)
 
headers = {
    'Apikey': "t5xX0LLizRkhF63izmJ7YUc6AiQHhs17",
    }
 
response = requests.get(url, headers=headers)
 
print(response.text)